// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PlanetPositions
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("planet")]
        public string Planet { get; set; }

        [JsonProperty("isBelowHorizon")]
        public bool IsBelowHorizon { get; set; }

        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("observer")]
        public Observer Observer { get; set; }

        [JsonProperty("rightAscension")]
        public HourAngle RightAscension { get; set; }

        [JsonProperty("declination")]
        public Declination Declination { get; set; }

        [JsonProperty("distance")]
        public Distance Distance { get; set; }

        [JsonProperty("siderealTime")]
        public HourAngle SiderealTime { get; set; }

        [JsonProperty("hourAngle")]
        public HourAngle HourAngle { get; set; }

        [JsonProperty("vectors")]
        public Vectors Vectors { get; set; }
    }

    public partial class Declination
    {
        [JsonProperty("degrees")]
        public long Degrees { get; set; }

        [JsonProperty("minutes")]
        public long Minutes { get; set; }

        [JsonProperty("seconds")]
        public long Seconds { get; set; }
    }

    public partial class Distance
    {
        [JsonProperty("km")]
        public double Km { get; set; }

        [JsonProperty("lightTravelSeconds")]
        public double LightTravelSeconds { get; set; }

        [JsonProperty("astronomicalUnits")]
        public double AstronomicalUnits { get; set; }
    }

    public partial class HourAngle
    {
        [JsonProperty("hours")]
        public long Hours { get; set; }

        [JsonProperty("minutes")]
        public long Minutes { get; set; }

        [JsonProperty("seconds")]
        public long Seconds { get; set; }
    }

    public partial class Observer
    {
        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }

    public partial class Vectors
    {
        [JsonProperty("x")]
        public double X { get; set; }

        [JsonProperty("y")]
        public double Y { get; set; }

        [JsonProperty("z")]
        public double Z { get; set; }
    }
}
